name: Commit Validations

on:
  pull_request:
    branches:
      - main

jobs:
  commit_lint:
    name: Run Commit Lint
    uses: zcode-gh/gitops-workflow/.github/workflows/commit-lint.yml@fe53ab0bb71dbaff2a7e9da4b012371790936e4d #v1.0.0
