name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    uses: zcode-gh/gitops-workflow/.github/workflows/release.yml@fe53ab0bb71dbaff2a7e9da4b012371790936e4d #v1.0.0
    with:
      owner: ${{ github.repository_owner }}
      repositories: ${{ github.event.repository.name }}
    secrets:
      github_app_id: ${{ secrets.CREATE_TOKEN_APP_ID }}
      github_app_private_key: ${{ secrets.CREATE_TOKEN_APP_PRIVATE_KEY }}
